### ISSUE TITLE
visibility Configuration was not worked in correct time

### ISSUE THREAD

**Issue by vpriya95** [websmurf/vue2-notify#13]
Hi,
I used the visibility configuration for 1 minute. But the notification is shown a few seconds only. can anyone give me a solution to show the notification for correct timing? I used the code like this

Vue.use(Notify,{visibility: 60000});

**Comment by websmurf** [comment]
Hi, sorry for the late reply, have checked it out, but I'm unable to reproduce this issue. 
Can you provide me with an example in a branch somewhere or on codepen or something so that I can check it out?

Both: 
```javascript
Vue.use(Notify, {visibility: 500})
```

And: 
```javascript
this.$notify('This is an advanced message', 'info', { visibility: 10000, iconClass: 'fa fa-lg fa-handshake-o', closeButtonClass: 'btn btn-default pull-right' })
```

Work as I would expect.

**Comment by websmurf** [comment]
Closed due to lack of response
