### ISSUE TITLE
notification appearing scrolls browser window to top instead of using relative viewport

### ISSUE THREAD

**Issue by Sirfrummel** [websmurf/vue2-notify#14]
I have a page that if I'm scrolled down, and do an action to trigger a notification, the browser snaps to the top, which is very jarring to the user-experience.  It would make sense that it should be the "top" of the relative viewport.

I tried switching to a position of 'bottom-right', but that still scrolls the window to the top.

**Comment by Sirfrummel** [comment]
Nevermind.. I'm an idiot.  The user was clicking a link in my app that had a `a href='#'` so that was what was causing it to jump to the top of the page.  All good now --

**Comment by websmurf** [comment]
Good to hear! :-)
