### ISSUE TITLE
$notify.setTypes is not a function

### ISSUE THREAD

**Issue by core01** [websmurf/vue2-notify#4]
Hello, thank you for the notify component and here the first issue:

> "vue": "^2.1.10"
> "velocity-animate": "^1.5.0",
> "vue2-notify": "^1.1.4"

main.js:
```
import Notify from 'vue2-notify';

const types = {
  info: {itemClass: 'notification is-info', iconClass: 'glyphicons glyphicons-info-sign'},
  success: {itemClass: 'notification is-success', iconClass: 'glyphicons glyphicons-ok'},
};

Vue.use(Notify);
Vue.$notify.setTypes(types);
```

Js build successfully, but in Chrome DevTools I see the next error:
`_WEBPACK_IMPORTED_MODULE_0_vue___default.a.$notify.setTypes is not a function`

**Comment by websmurf** [comment]
Fixed in release 1.2.0
